name: Scrape and Post Articles

on:
  schedule:
    # Run twice a day: at 8:00 AM and 8:00 PM UTC
    - cron: '0 8,20 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run scraper
        run: node scripts/test-full-process.js
        env:
          WORDPRESS_API_URL: ${{ secrets.WORDPRESS_API_URL }}
          WORDPRESS_CLIENT_ID: ${{ secrets.WORDPRESS_CLIENT_ID }}
          WORDPRESS_CLIENT_SECRET: ${{ secrets.WORDPRESS_CLIENT_SECRET }}
          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          TARGET_WEBSITE: 'https://civil.ge/ka/archives/category/news-ka,https://www.interpressnews.ge/ka/category/11-samartali/'

      - name: Generate sitemap
        run: node scripts/generate-sitemap.js
        env:
          WORDPRESS_API_URL: ${{ secrets.WORDPRESS_API_URL }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}

      - name: Commit and push sitemap changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add public/sitemap.xml
          git commit -m "Update sitemap after article scraping [skip ci]" || echo "No changes to commit"
          git push
